export const LOGIN = "LOGIN";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

export const LOAD_USER = "LOAD_USER";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT = "LOGOUT";

//// Profile Types

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";

export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const CREATE_OR_UPDATE_USER_PROFILE = "CREATE_OR_UPDATE_USER_PROFILE";
export const CREATE_OR_UPDATE_USER_PROFILE_SUCCESS =
  "CREATE_OR_UPDATE_USER_PROFILE_SUCCESS";
export const CREATE_OR_UPDATE_USER_PROFILE_ERROR =
  "CREATE_OR_UPDATE_USER_PROFILE_ERROR";

export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";
export const ADD_EXPERIENCE_ERROR = "ADD_EXPERIENCE_ERROR";

export const ADD_EDUCATION = "ADD_EDUCATION";
export const ADD_EDUCATION_SUCCESS = "ADD_EDUCATION_SUCCESS";
export const ADD_EDUCATION_ERROR = "ADD_EDUCATION_ERROR";

export const DELETE_EDUCATION = "DELETE_EDUCATION";
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS";
export const DELETE_EDUCATION_ERROR = "DELETE_EDUCATION_ERROR";

export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS";
export const DELETE_EXPERIENCE_ERROR = "DELETE_EXPERIENCE_ERROR";

export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_ERROR = "DELETE_ACCOUNT_ERROR";

export const GET_ALL_USER_PROFILE = "GET_ALL_USER_PROFILE";
export const GET_ALL_USER_PROFILE_SUCCESS = "GET_ALL_USER_PROFILE_SUCCESS";
export const GET_ALL_USER_PROFILE_ERROR = "GET_ALL_USER_PROFILE_ERROR";

export const GET_USER_PROFILE_BY_ID = "GET_USER_PROFILE_BY_ID";
export const GET_USER_PROFILE_BY_ID_SUCCESS = "GET_USER_PROFILE_BY_ID_SUCCESS";
export const GET_USER_PROFILE_BY_ID_ERROR = "GET_USER_PROFILE_BY_ID_ERROR";

export const GET_GITHUB_REPO = "GET_GITHUB_REPO";
export const GET_GITHUB_REPO_SUCCESS = "GET_GITHUB_REPO_SUCCESS";
export const GET_GITHUB_REPO_ERROR = "GET_GITHUB_REPO_ERROR";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";

export const LIKE_POST = "LIKE_POST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";

export const UNLIKE_POST = "UNLIKE_POST";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";
export const UNLIKE_POST_ERROR = "UNLIKE_POST_ERROR";

export const GET_ALL_POST = "GET_ALL_POST";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_ERROR = "GET_ALL_POST_ERROR";

export const GET_SINGLE_POST = "GET_SINGLE_POST";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
export const GET_SINGLE_POST_ERROR = "GET_SINGLE_POST_ERROR";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";

export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";

export const PROFILE_IMAGE = "PROFILE_IMAGE";
export const PROFILE_IMAGE_SUCCESS = "PROFILE_IMAGE_SUCCESS";
export const PROFILE_IMAGE_ERROR = "PROFILE_IMAGE_ERROR";
